# Uncomment this line to define a global platform for your project
platform :ios, '8.0'


target 'WeiBoPro' do
use_frameworks!
pod "AFNetworking"
pod "SDWebImage"
pod "YYModel"
pod "FMDB"
pod "SVProgressHUD"
pod "pop"
pod "SnapKit"
end

